// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjUDs_1mCPkekrQ0ISjlT4XMIr48KRZo',
    appId: '1:294441691064:web:2cf7097758daabb8ab114d',
    messagingSenderId: '294441691064',
    projectId: 'vault-notes-vrutsa',
    authDomain: 'vault-notes-vrutsa.firebaseapp.com',
    storageBucket: 'vault-notes-vrutsa.firebasestorage.app',
    measurementId: 'G-9G9RL8GSCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnYYsDh3TWI83ORTsLCeyVJgqajpFhQr0',
    appId: '1:294441691064:android:a3c40e8780f7fef2ab114d',
    messagingSenderId: '294441691064',
    projectId: 'vault-notes-vrutsa',
    storageBucket: 'vault-notes-vrutsa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjUDs_1mCPkekrQ0ISjlT4XMIr48KRZo',
    appId: '1:294441691064:web:7026eb13b6b0880bab114d',
    messagingSenderId: '294441691064',
    projectId: 'vault-notes-vrutsa',
    authDomain: 'vault-notes-vrutsa.firebaseapp.com',
    storageBucket: 'vault-notes-vrutsa.firebasestorage.app',
    measurementId: 'G-REDNWC3RY0',
  );
}
