// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4ZlYPlYD82d1CHoaong-Q_mc2sKk2nM',
    appId: '1:1034669878006:web:3fba0cbac404a515581ad7',
    messagingSenderId: '1034669878006',
    projectId: 'notes-case-7c81e',
    authDomain: 'notes-case-7c81e.firebaseapp.com',
    storageBucket: 'notes-case-7c81e.firebasestorage.app',
    measurementId: 'G-6DWJT64RM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3M_hMuwdurdvX3Ujz9KOnh7L858zYDCU',
    appId: '1:1034669878006:android:e20bac32d7a001c8581ad7',
    messagingSenderId: '1034669878006',
    projectId: 'notes-case-7c81e',
    storageBucket: 'notes-case-7c81e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4ZlYPlYD82d1CHoaong-Q_mc2sKk2nM',
    appId: '1:1034669878006:web:b2f5358cb96696f4581ad7',
    messagingSenderId: '1034669878006',
    projectId: 'notes-case-7c81e',
    authDomain: 'notes-case-7c81e.firebaseapp.com',
    storageBucket: 'notes-case-7c81e.firebasestorage.app',
    measurementId: 'G-TR56J020HE',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDmwNvpMFF1RMDEFqJ4CJ2MzBwzTHXCH4',
    appId: '1:1034669878006:ios:9a6b9e75e5f3fe35581ad7',
    messagingSenderId: '1034669878006',
    projectId: 'notes-case-7c81e',
    storageBucket: 'notes-case-7c81e.firebasestorage.app',
    iosClientId: '1034669878006-1ql6q8rm6217tnfdtdgha0uge7edfgub.apps.googleusercontent.com',
    iosBundleId: 'notes-case.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDmwNvpMFF1RMDEFqJ4CJ2MzBwzTHXCH4',
    appId: '1:1034669878006:ios:45c8c9742f2d3761581ad7',
    messagingSenderId: '1034669878006',
    projectId: 'notes-case-7c81e',
    storageBucket: 'notes-case-7c81e.firebasestorage.app',
    iosClientId: '1034669878006-j90uonnp4u93qkpmligmh08h8rm42s6v.apps.googleusercontent.com',
    iosBundleId: 'notes-case.com',
  );
}
